# Generated by Django 5.0.4 on 2024-05-02 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcdSafeAcnt',
            fields=[
                ('a_uid', models.BigIntegerField(db_comment='SAFE Unique Account ID', primary_key=True, serialize=False)),
                ('acct_type', models.CharField(db_comment='Account Type - Checking (C)/ Savings (S)/ Loan (L)', max_length=2, unique=True)),
                ('acct_name', models.CharField(db_comment='Account Name', max_length=30)),
                ('a_street', models.CharField(db_comment='Account Street Address', max_length=30)),
                ('a_city', models.CharField(db_comment='Account City Location', max_length=30)),
                ('a_state', models.CharField(db_comment='Account State Code - Ex: New York: NY', max_length=2)),
                ('a_zipcode', models.CharField(db_comment='Account Zipcode', max_length=5)),
            ],
            options={
                'db_table': 'acd_safe_acnt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AcdCustomer',
            fields=[
                ('c_id', models.IntegerField(db_comment='Unique Customer ID', primary_key=True, serialize=False)),
                ('c_fname', models.CharField(db_comment='Customer First Name', max_length=30)),
                ('c_lname', models.CharField(db_comment='Customer Last Name', max_length=30)),
                ('c_street', models.CharField(db_comment='Customer Street - Address Line 1', max_length=30)),
                ('c_city', models.CharField(db_comment='Customer City Location', max_length=30)),
                ('c_state', models.CharField(db_comment='Customer State Code - Ex: New York: NY', max_length=2)),
                ('c_zipcode', models.CharField(db_comment='Customer Zipcode', max_length=5)),
            ],
            options={
                'db_table': 'acd_customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AcdInstitute',
            fields=[
                ('inst_code', models.IntegerField(db_comment='Unique Institute Code', primary_key=True, serialize=False)),
                ('inst_name', models.CharField(db_comment='Institute Name (University Name)', max_length=30)),
            ],
            options={
                'db_table': 'acd_institute',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AcdInsurance',
            fields=[
                ('ins_acct_no', models.BigIntegerField(db_comment='Home Insurance Unique Account Number', primary_key=True, serialize=False)),
                ('ins_company', models.CharField(db_comment='Insurance Company Name', max_length=30)),
                ('ins_street', models.CharField(db_comment='Insurance Street Address', max_length=30)),
                ('ins_city', models.CharField(db_comment='Insurance City Location', max_length=30)),
                ('ins_state', models.CharField(db_comment='Insurance State Code- Ex: New York: NY', max_length=2)),
                ('ins_zipcode', models.CharField(db_comment="Insurance Company's Zipcode", max_length=5)),
                ('yearly_prm', models.DecimalField(db_comment='Insurance Yearly Premium', decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'acd_insurance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomersCustomer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'customers_customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AcdChecking',
            fields=[
                ('a_uid', models.OneToOneField(db_column='a_uid', db_comment='SAFE Unique Account ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='customers.acdsafeacnt')),
                ('acct_no', models.BigIntegerField(db_comment='Checking Account Unique Account Number', unique=True)),
                ('date_open', models.DateTimeField(db_comment='Account Opening Date')),
                ('serv_charge', models.DecimalField(db_comment='Account Service Charge', decimal_places=2, max_digits=6)),
            ],
            options={
                'db_table': 'acd_checking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AcdLoan',
            fields=[
                ('a_uid', models.OneToOneField(db_column='a_uid', db_comment='SAFE Unique Account ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='customers.acdsafeacnt')),
                ('acct_no', models.BigIntegerField(db_comment='Loan Account Unique Account Number')),
                ('loan_type', models.CharField(db_comment='Loan Type - Student (SL)/ Home (HL)/ Personal (PL)', max_length=2)),
                ('loan_amt', models.DecimalField(db_comment='OVERALL LOAN AMOUNT ', decimal_places=2, max_digits=10)),
                ('loan_rate', models.DecimalField(db_comment='LOAN INTEREST RATE', decimal_places=2, max_digits=4)),
                ('loan_months', models.SmallIntegerField(db_comment='LOAN DURATION')),
                ('loan_payment', models.DecimalField(db_comment='LOAN REPAYMENT PER MONTH', decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'acd_loan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AcdSavings',
            fields=[
                ('a_uid', models.OneToOneField(db_column='a_uid', db_comment='SAFE Unique Account ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='customers.acdsafeacnt')),
                ('acct_no', models.BigIntegerField(db_comment='Savings Account Unique Account Number', unique=True)),
                ('date_open', models.DateTimeField(db_comment='Savings Account Opening Date')),
                ('intrst_rate', models.DecimalField(db_comment='Interest Rate', decimal_places=2, max_digits=4)),
            ],
            options={
                'db_table': 'acd_savings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AcdHome',
            fields=[
                ('a_uid', models.OneToOneField(db_column='a_uid', db_comment='SAFE Unique Account ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='customers.acdloan')),
                ('hl_uid', models.IntegerField(db_comment='Home Loan Unique Loan ID', unique=True)),
                ('date_open', models.DateTimeField(db_comment='Home Loan Account Opening Date')),
                ('built_year', models.SmallIntegerField(db_comment='Home Built Year')),
            ],
            options={
                'db_table': 'acd_home',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AcdPersonal',
            fields=[
                ('a_uid', models.OneToOneField(db_column='a_uid', db_comment='SAFE Unique Account ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='customers.acdloan')),
                ('pl_uid', models.IntegerField(db_comment='Personal Loan Unique ID', unique=True)),
                ('date_open', models.DateTimeField(db_comment='Personal Loan Account Opening Date')),
            ],
            options={
                'db_table': 'acd_personal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AcdStudent',
            fields=[
                ('a_uid', models.OneToOneField(db_column='a_uid', db_comment='SAFE Unique Account ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='customers.acdloan')),
                ('sl_uid', models.FloatField(db_comment='Student Loan Unique Loan ID', unique=True)),
                ('date_open', models.DateTimeField(db_comment='Student Loan Account Opening Date')),
                ('student_id', models.CharField(db_comment='Student ID From Institute', max_length=6)),
                ('degree_type', models.CharField(db_comment='Degree Type - Graduate / Undergraduate', max_length=13)),
                ('grad_month', models.CharField(db_comment='Graduation Month', max_length=10)),
                ('grad_year', models.SmallIntegerField(db_comment='Graduation Year')),
            ],
            options={
                'db_table': 'acd_student',
                'managed': False,
            },
        ),
    ]
