# Generated by Django 5.0.4 on 2024-05-03 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_acdsafeacnt_acdcustomer_acdinstitute_acdinsurance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuth',
            fields=[
                ('username', models.BigIntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'UserAuth',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='acdchecking',
            table='AcdChecking',
        ),
        migrations.AlterModelTable(
            name='acdcustomer',
            table='AcdCustomer',
        ),
        migrations.AlterModelTable(
            name='acdhome',
            table='AcdHome',
        ),
        migrations.AlterModelTable(
            name='acdinstitute',
            table='AcdInstitute',
        ),
        migrations.AlterModelTable(
            name='acdinsurance',
            table='AcdInsurance',
        ),
        migrations.AlterModelTable(
            name='acdloan',
            table='AcdLoan',
        ),
        migrations.AlterModelTable(
            name='acdpersonal',
            table='AcdPersonal',
        ),
        migrations.AlterModelTable(
            name='acdsafeacnt',
            table='AcdSafeAcnt',
        ),
        migrations.AlterModelTable(
            name='acdsavings',
            table='AcdSavings',
        ),
        migrations.AlterModelTable(
            name='acdstudent',
            table='AcdStudent',
        ),
    ]
