# Generated by Django 5.0.4 on 2024-05-03 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_userauth_alter_acdchecking_table_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAuth',
        ),
        migrations.AlterModelTable(
            name='acdchecking',
            table='acd_checking',
        ),
        migrations.AlterModelTable(
            name='acdcustomer',
            table='acd_customer',
        ),
        migrations.AlterModelTable(
            name='acdhome',
            table='acd_home',
        ),
        migrations.AlterModelTable(
            name='acdinstitute',
            table='acd_institute',
        ),
        migrations.AlterModelTable(
            name='acdinsurance',
            table='acd_insurance',
        ),
        migrations.AlterModelTable(
            name='acdloan',
            table='acd_loan',
        ),
        migrations.AlterModelTable(
            name='acdpersonal',
            table='acd_personal',
        ),
        migrations.AlterModelTable(
            name='acdsafeacnt',
            table='acd_safe_acnt',
        ),
        migrations.AlterModelTable(
            name='acdsavings',
            table='acd_savings',
        ),
        migrations.AlterModelTable(
            name='acdstudent',
            table='acd_student',
        ),
    ]
